"""A synthetic CS2 stats install for tools/package.py --ci, so every push runs the whole stats path (CS2's
items_game.txt -> prep's write_stats -> weapon_stats.json -> the game's own reader and Weapons.gd) on all
weapons.json guns instead of on class rows alone.
build(root, out) writes out/cs2/scripts/items/items_game.txt, then runs the repo's prep_cs2.write_stats on it
(out/cs2/weapon_stats.json) and returns (problems, warnings) exactly as setup would report them.
The file is generated, not copied from CS2. Its layout follows CS:GO's items_game.txt as
prep/tests/fixtures/items_game.txt does (prefab chains through class prefabs, a second "prefabs" section,
attributes in plain and block form, [$X360] / [!$WIN32] conditionals, item entries with blocks ahead of
"name", escaped quotes). The numbers are test values: each gun gets its class row of
sheets/weapon_defaults.json, its own recoil seed, and on its item entry every per-gun value the sheets claim
as CS2's (known()), so the game's stats_reference and the lobby's shots-to-kill checks run on prep's output.
None of it is a CS2 fact (those sheet values are themselves labelled unverified)."""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ITEMS_GAME = os.path.join("cs2", "scripts", "items", "items_game.txt")
# class-level attributes (on the class prefab) and gun-level ones (on <weapon>_prefab): attribute -> column
CLASS_KEYS = {"headshot multiplier": "headshot", "penetration": "penetration", "range": "range", "range modifier": "range_modifier",
              "armor ratio": "armor_ratio", "primary reserve ammo max": "reserve", "inaccuracy jump initial": "inacc_jump",
              "inaccuracy land": "inacc_land", "max player speed": "max_speed", "bullets": "bullets"}
GUN_KEYS = {"damage": "damage", "cycletime": "cycletime", "primary clip size": "clip", "spread": "spread",
            "inaccuracy stand": "inacc_stand", "inaccuracy crouch": "inacc_crouch", "inaccuracy move": "inacc_move",
            "inaccuracy fire": "inacc_fire", "recoil angle": "recoil_angle", "recoil angle variance": "recoil_angle_var",
            "recoil magnitude": "recoil_mag", "recoil magnitude variance": "recoil_mag_var",
            "recovery time stand": "recovery_stand", "recovery time crouch": "recovery_crouch"}
SLOT = {"pistol": "secondary", "gear": "secondary"}


def _num(v):
    if isinstance(v, bool):
        return "1" if v else "0"
    return ("%.6f" % v) if isinstance(v, float) else str(v)


def _attr(k, v, block=False):
    if block:
        return '\t\t\t\t"%s"\n\t\t\t\t{\n\t\t\t\t\t"attribute_class"\t\t"%s"\n\t\t\t\t\t"value"\t\t"%s"\n\t\t\t\t}\n' % (k, k.replace(" ", "_"), v)
    return '\t\t\t\t"%s"\t\t"%s"\n' % (k, v)


def known(root):
    """{weapon id: {attribute: value}}: every per-gun number the sheets hold as CS2's (weapon_defaults "reference"
    rows, aim_lobby "stk_checks" damage / armor ratio / headshot multiplier). Two sheets naming different values
    for one stat raise, since one install cannot satisfy both."""
    sys.path.insert(0, os.path.join(root, "prep"))
    import prep_cs2
    out = {}
    def put(w, k, v):
        have = out.setdefault(w, {})
        if k in have and abs(float(have[k]) - float(v)) > 1e-9:
            raise ValueError("the sheets disagree on %s %s: %s and %s" % (w, k, have[k], v))
        have[k] = v
    for r in prep_cs2.sheet("weapon_defaults", os.path.join(root, "sheets")).get("reference", []):
        put(r["weapon"], r["key"], r["value"])
    for r in prep_cs2.sheet("aim_lobby", os.path.join(root, "sheets")).get("stk_checks", []):
        for k, c in (("damage", "damage"), ("armor ratio", "armor_ratio"), ("headshot multiplier", "hs_mult")):
            put(r["weapon"], k, r[c])
    return out


def items_game_text(guns, classes, own):
    """guns: weapons.json cs2 rows; classes: weapon_defaults rows by id; own: known() (on each gun's item entry)."""
    out = ["// Generated by prep/tests/ci_data.py for tools/package.py --ci. Not copied from CS2: the layout follows",
           "// CS:GO's items_game.txt, the numbers are weapon_defaults.json class rows and test values.",
           '"items_game"', "{", '\t"prefabs"', "\t{"]
    out.append('\t\t"weapon_base"\n\t\t{\n\t\t\t"item_class"\t\t"weapon_base"\n\t\t\t"attributes"\n\t\t\t{\n' + _attr("in game price", "0") + "\t\t\t}\n\t\t}")
    out.append('\t\t"statted_item_base"\n\t\t{\n\t\t\t"attributes"\n\t\t\t{\n' + _attr("kill eater score type", "0", block=True) + "\t\t\t}\n\t\t}")
    for s in ("primary", "secondary"):
        out.append('\t\t"%s"\n\t\t{\n\t\t\t"prefab"\t\t"weapon_base"\n\t\t\t"item_slot"\t\t"%s"\n\t\t}' % (s, s))
    for cls in sorted({g["slot"] for g in guns}):
        row = classes[cls]
        body = "".join(_attr(k, _num(row[c])) for k, c in sorted(CLASS_KEYS.items()))
        body += _attr("max player speed", "1", False).rstrip("\n") + "\t\t[!$WIN32]\n"  # a console value the PC build never plays
        body += _attr("is full auto", _num(bool(row["full_auto"])))
        out.append('\t\t"%s_class"\n\t\t{\n\t\t\t"prefab"\t\t"%s"\n\t\t\t"attributes"\n\t\t\t{\n%s\t\t\t}\n\t\t}' % (cls, SLOT.get(cls, "primary"), body))
    late = []
    for i, g in enumerate(guns):
        row = classes[g["slot"]]
        body = ""
        for k, c in sorted(GUN_KEYS.items()):
            body += _attr(k, _num(row[c]))
            if k == "damage":
                body += _attr(k, "999").rstrip("\n") + "\t\t[$X360]\n"
        body += _attr("recoil seed", str(101 + 37 * i), block=i % 4 == 1)
        if g["alt"] == "scope":
            body += _attr("zoom levels", _num(row["zoom_levels"])) + _attr("max player speed alt", _num(row["max_speed_alt"]))
        elif g["alt"] == "silencer":
            body += _attr("has silencer", "1")
        elif g["alt"] == "burst":
            body += _attr("has burst mode", "1")
        blk = '\t\t"%s_prefab"\n\t\t{\n\t\t\t"prefab"\t\t"%s_class statted_item_base"\n\t\t\t"item_class"\t\t"%s"\n\t\t\t"attributes"\n\t\t\t{\n%s\t\t\t}\n\t\t}' % (
            g["item"], g["slot"], g["item"], body)
        (late if i % 3 == 2 else out).append(blk)
    out += ["\t}", "\t// a second section: blocks merge as in the real file's include order", '\t"prefabs"', "\t{"] + late + ["\t}", '\t"items"', "\t{"]
    for i, g in enumerate(guns):
        attrs = "".join(_attr(k, _num(v)) for k, v in sorted(own.get(g["id"], {}).items()))
        attrs = '\t\t\t"attributes"\n\t\t\t{\n%s\t\t\t}\n' % attrs if attrs else ""
        visuals = '\t\t\t"visuals"\n\t\t\t{\n\t\t\t\t"weapon_type"\t\t"%s"\n\t\t\t}\n' % g["slot"]
        head = '\t\t\t"name"\t\t"%s"\n\t\t\t"prefab"\t\t"%s_prefab"\n\t\t\t"item_description"\t\t"Test \\"%s\\" {not a block}"\n' % (g["item"], g["item"], g["name"])
        body = (visuals + attrs + head) if i % 4 == 0 else (head + attrs + visuals)  # some entries (the AK, Glock, Deagle) hold blocks ahead of "name"
        out.append('\t\t"%d"\n\t\t{\n%s\t\t}' % (i + 1, body))
    out += ["\t}", "}", ""]
    return "\n".join(out)


def build(root, out):
    """Writes the synthetic install under out and runs prep's write_stats on it; returns (problems, warnings)."""
    prep = os.path.join(root, "prep")
    if prep not in sys.path:
        sys.path.insert(0, prep)
    import prep_cs2
    wd = prep_cs2.sheet("weapon_defaults", os.path.join(root, "sheets"))
    ws = prep_cs2.sheet("weapons", prep)
    guns = prep_cs2.weapon_rows(ws)
    p = os.path.join(out, ITEMS_GAME)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "w", encoding="utf-8", newline="\n") as f:
        f.write(items_game_text(guns, {r["id"]: r for r in wd["rows"]}, known(root)))
    return prep_cs2.write_stats(os.path.join(out, "cs2"), ws, prep)


if __name__ == "__main__":
    print(build(os.path.dirname(os.path.dirname(HERE)), sys.argv[1]))
